### ISSUE TITLE
Add Typescript

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/battlemath#52]
Add typescript to project.

**Comment by ayrbox** [comment]
@JesseRWeigel can you assign this to me?

**Comment by ayrbox** [comment]
@JesseRWeigel  
I am very little experience with ReactNative (only worked in 3 projects) and I did not know about `react-native-web` until we talked about it in this thread #74 

When I go through documentation of [React Native Web](https://necolas.github.io/react-native-web/) I understood that the project is mainly to convert react-native app to web app.  Will the project be able to published as mobile app with project built from `create-react-app`?   If not will it be good idea that I port the project to ReactNative and add `react-native-web`.

**Comment by JesseRWeigel** [comment]
Maybe it would be better just to leave the project as a react site at this point. It would be easier to maintain. We would just need to convert the small amount of ui to normal html elements and remove react-native-web. What do you think?

**Comment by ayrbox** [comment]
Sounds good to me. 
I've added the typescript and converted all the js file to tsx.

**Comment by JesseRWeigel** [comment]
Awesome! Thank you!
