### ISSUE TITLE
Add Contributing Guide

### ISSUE THREAD

**Issue by BekahHW** [JesseRWeigel/battlemath#55]
- Add a contributing guide to onboard new contributors.

### Examples
- [Virtual Coffee](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/CONTRIBUTING.md)
- [Deepgram](https://github.com/deepgram-devs/deepgram-go-sdk/blob/main/CONTRIBUTING.md)

**Comment by piyush-panpaliya** [comment]
@JesseRWeigel  github url are still not updated this clicking on the index url redirects to virtualcoffee readme

**Comment by JesseRWeigel** [comment]
You are right. Looks like some of the links still go to VC. Let's reopen this and fix all the links.

**Comment by piyush-panpaliya** [comment]
Created a pr please merge it if it is correct (#77 )
