### ISSUE TITLE
Add a points system

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/battlemath#61]
Could start out very basic but could grow to include:
- Saving game progress or high scores
- Allowing multiple users to save to different user profiles

Any saving of data should be done locally in localStorage. I don't want to get into a real database for the first version.

**Comment by piyush-panpaliya** [comment]
Hey I would like to work on this, I will be adding the feature to save high score and game progress.
please assign this to me

**Comment by JesseRWeigel** [comment]
Thank you!

**Comment by piyush-panpaliya** [comment]
@JesseRWeigel  created a PR(#79),please check it and merge if its all correct.

Also the website which is live right now([jesserweigel.github.io/battlemath/](https://jesserweigel.github.io/battlemath/))
is not **up to date**
