### ISSUE TITLE
Add background music to game

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/battlemath#64]
Advice from an 8 year old user. Specifically he asked for "arcade game music".

At some point we may want to add:
-  sound effects for correct and incorrect answers
- music or sounds for victory
- different music for each game mode
- different music when the number of enemies is very large or small

**Comment by ayrbox** [comment]
@JesseRWeigel 
What do you think about these sounds for background? https://www.dargolan-free.com/video-game-music

**Comment by JesseRWeigel** [comment]
I really like number 7 "flying". Not too fast that it is distracting, but not too slow that it puts you to sleep.
