### ISSUE TITLE
Update to use createRoot

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/battlemath#70]
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

Please follow the instructions to update this.

**Comment by Athi223** [comment]
Hey @JesseRWeigel,
I'd like to contribute to this, if its available
