### ISSUE TITLE
Why React Native and React Native Web?

### ISSUE THREAD

**Issue by ayrbox** [JesseRWeigel/battlemath#74]
Hey @JesseRWeigel ,

Sorry if its noob question. I do not understand why are we using ReactNative and React Native Web?

Is it to make sure the app is portable to reactnative without any code change?

**Comment by JesseRWeigel** [comment]
Yep, you are correct. I would like to release the game as a mobile app and a web app. Right now I just want to focus on the web app, but I would like to have one codebase for both if possible.

**Comment by ayrbox** [comment]
That great.
