### ISSUE TITLE
Add only-allow to the project

### ISSUE THREAD

**Issue by JesseRWeigel** [JesseRWeigel/battlemath#91]
I would like to use `only-allow` with this project so that yarn is only used. It has been implemented here ( [https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/package.json](https://github.com/Virtual-Coffee/virtualcoffee.io/blob/main/package.json) ) in the Virtual Coffee repo. We can use that as an example.

**Comment by Vinitvh** [comment]
Hi, can I work on this?
