### ISSUE TITLE
Change background color for Multiplication

### ISSUE THREAD

**Issue by annakimdev** [JesseRWeigel/battlemath#99]
**Describe the bug**
White text against Yellow background is not visible.

**To Reproduce**
1. Go to 'Multiplication'
2. Type answer in the input box

**Expected behavior**
Number should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/102593061/198488247-f6ba2417-9bfe-4e88-b173-4a341e70ed4b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 107

**Resolution**
Recommended color [palette](https://coolors.co/ffcccc-ff9900-2e282a-087e8b):
Metallic Seaweed: rgb(8,126,139)
![image](https://user-images.githubusercontent.com/102593061/198492524-621f0c56-a960-4655-8253-939baa02acbd.png)

**Comment by JesseRWeigel** [comment]
This is a great idea! If you would like to implement it, I can assign it to you.

**Comment by annakimdev** [comment]
I'd love to. Please assign to me. Thank you!
